#!/bin/bash
declare -A arr
function set_value {
arr+=([$1]=$2)
}
function get_value {
echo ${arr[$1]}
}
function del_value {
for key in ${!arr[@]}; do
if [ "$key" == "$1" ]; then
#unset arr[$key]
arr[$key]="#tombstone#"
fi
done
}

arr["key1"]=val1
arr+=(["key2"]=val2)
arr+=(["key3"]=val3)
#set_value
set_value key4 val5
for key in ${!arr[@]}; do
echo ${key} ${arr[${key}]}
done
#get_value
echo " "
get_value key3
#del_value
echo " "
del_value key3
for key in ${!arr[@]}; do
echo ${key} ${arr[${key}]}
done

set_value key3 val9

del_value key2
echo " "
for key in ${!arr[@]}; do
echo ${key} ${arr[${key}]}
done
unset arr
